<a href="https://colab.research.google.com/github/apxunov/intelligent-data-analysis/blob/main/hometask1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Домашнее задание 1**

## **Описание данных**
В папке Data в Google Disk'е находится информация о студентах в файлах формата .csv. Всего 10 групп студентов. <br>
Файлы делятся на две категории:
* Students_info_i - информация о студентах из группы i
* Students_marks_i - оценки студентов из группы i за экзамены

In [ ]:
import os
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')
dir_ = "/content/drive/MyDrive/Colab Notebooks/iad/hometask1/Data/"

Mounted at /content/drive

##**Задание 1.**
Соберём всю информацию о студентах в одну таблицу df. <br>
В получившейся таблице будет информация и оценки всех студентов из всех групп.

In [ ]:
from glob import glob


studentsInfo = glob(f"{dir_}*info*.csv")
studentsInfoDf = pd.concat([pd.read_csv(f) for f in studentsInfo])

studentsMarks = glob(f"{dir_}*marks*.csv")
studentsMarksDf = pd.concat([pd.read_csv(f) for f in studentsMarks])

df = pd.merge(studentsInfoDf, studentsMarksDf).sort_values(by='index', ascending=True, ignore_index=True)
df

     index  gender race/ethnicity  ... math score reading score writing score
0        0  female        group B  ...         72            72            74
1        1  female        group C  ...         69            90            88
2        2  female        group B  ...         90            95            93
3        3    male        group A  ...         47            57            44
4        4    male        group C  ...         76            78            75
..     ...     ...            ...  ...        ...           ...           ...
995    995  female        group E  ...         88            99            95
996    996    male        group C  ...         62            55            55
997    997  female        group C  ...         59            71            65
998    998  female        group D  ...         68            78            77
999    999  female        group D  ...         77            86            86

[1000 rows x 10 columns]

## **Задание 2.**## 
Удалим столбец index у полученной таблицы. <br>
Выведем первые 10 строк таблицы.

In [ ]:
df.drop('index', axis='columns', inplace=True)
df.head(10)

   gender race/ethnicity  ... reading score writing score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75
5  female        group B  ...            83            78
6  female        group B  ...            95            92
7    male        group B  ...            43            39
8    male        group D  ...            64            67
9  female        group B  ...            60            50

[10 rows x 9 columns]

## **Задание 3.**## 
Выведем размер полученной таблицы. <br>
(`rows, cols`)

In [ ]:
df.shape

(1000, 9)

## **Задание 4.**## 
Выведем на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение).

In [ ]:
def getStats(df, colName):
  stats = df[colName].describe()
  stats.name = colName

  min = stats['min']
  max = stats['max']
  meanval = stats['mean']
  std = stats['std']

  statsArr = pd.DataFrame({'Статическая характеристика': ['Минимум', 'Максимум', 'Среднее значение', 'Стандартное отклонение'],
                          'Показатель': [min, max, meanval, std]})

  return statsArr

In [ ]:
mathStats = getStats(df, 'math score')
mathStats

  Статическая характеристика  Показатель
0                    Минимум     0.00000
1                   Максимум   100.00000
2           Среднее значение    66.08900
3     Стандартное отклонение    15.16308

In [ ]:
readingStats = getStats(df, 'reading score')
readingStats

  Статическая характеристика  Показатель
0                    Минимум   17.000000
1                   Максимум  100.000000
2           Среднее значение   69.169000
3     Стандартное отклонение   14.600192

In [ ]:
writingStats = getStats(df, 'writing score')
writingStats

  Статическая характеристика  Показатель
0                    Минимум   10.000000
1                   Максимум  100.000000
2           Среднее значение   68.054000
3     Стандартное отклонение   15.195657

## **Задание 5.**## 
Проверим, есть ли в таблице пропущенные значения.

In [ ]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
group                          0
math score                     0
reading score                  0
writing score                  0
dtype: int64

Как видим, пропущенных значений нет.

## **Задание 6.**## 
Выведем на экран средние баллы студентов по каждому предмету (math, reading, writing).

In [ ]:
def getAvgScore(df, subj_arr, stats={}):
  for i in subj_arr:
    stats[i.replace(' score', '')] = df[i].describe()['mean']
  return stats

getAvgScore(df, ['math score', 'reading score', 'writing score'])

{'math': 66.089, 'reading': 69.169, 'writing': 68.054}

Выведу также средние баллы студента по трем предметам в столбец mean – на случай, если выше я неверно понял формулировку

In [ ]:
subjectsArrayDf = [df['math score'], df['reading score'], df['writing score']]
subjectsDf = (pd.DataFrame(subjectsArrayDf, index=['math score', 'reading score', 'writing score'])).T

subjectsDf

     math score  reading score  writing score
0            72             72             74
1            69             90             88
2            90             95             93
3            47             57             44
4            76             78             75
..          ...            ...            ...
995          88             99             95
996          62             55             55
997          59             71             65
998          68             78             77
999          77             86             86

[1000 rows x 3 columns]

In [ ]:
subjectsDf['mean'] = subjectsDf.mean(axis=1)
subjectsDf

     math score  reading score  writing score       mean
0            72             72             74  72.666667
1            69             90             88  82.333333
2            90             95             93  92.666667
3            47             57             44  49.333333
4            76             78             75  76.333333
..          ...            ...            ...        ...
995          88             99             95  94.000000
996          62             55             55  57.333333
997          59             71             65  65.000000
998          68             78             77  74.333333
999          77             86             86  83.000000

[1000 rows x 4 columns]

## **Задание 7.**## 
Узнаем, как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (`test preparation course`). <br>
Выведем на экран <b>для каждого предмета в отдельности</b> средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.

In [ ]:
TestDf = pd.DataFrame(df, columns = ['gender', 'test preparation course', 'math score', 'reading score', 'writing score'])

studentsPassedPrepTest = TestDf[TestDf['test preparation course']=='completed']
studentsDidntPassPrepTest = TestDf[TestDf['test preparation course']=='none']

subjectsList = ['math score', 'reading score', 'writing score']
def showAvgScorePerSubject(df):
  meanScores = {i: df[i].mean() for i in subjectsList}
  return meanScores

print("Those, who \033[1m passed \033[0m preparation test: ",showAvgScorePerSubject(studentsPassedPrepTest))
print("Those, who \033[1m didn't pass \033[0m preparation test: ",showAvgScorePerSubject(studentsDidntPassPrepTest))

Those, who  passed  preparation test:  {'math score': 69.69553072625699, 'reading score': 73.89385474860335, 'writing score': 74.41899441340782}
Those, who  didn't pass  preparation test:  {'math score': 64.0778816199377, 'reading score': 66.53426791277259, 'writing score': 64.50467289719626}

## **Задание 8.**## 
Выведем на экран все различные значения из столбца `lunch`.

In [ ]:
pd.unique(df['lunch']).tolist()

['standard', 'free/reduced']

## **Задание 9.**## 
 Переименуем колонку "parental level of education" в "education", а "test preparation course" в "test preparation" <br> с помощью метода `pandas rename`.

Было:

In [ ]:
df

     gender race/ethnicity  ... reading score writing score
0    female        group B  ...            72            74
1    female        group C  ...            90            88
2    female        group B  ...            95            93
3      male        group A  ...            57            44
4      male        group C  ...            78            75
..      ...            ...  ...           ...           ...
995  female        group E  ...            99            95
996    male        group C  ...            55            55
997  female        group C  ...            71            65
998  female        group D  ...            78            77
999  female        group D  ...            86            86

[1000 rows x 9 columns]

Стало:

In [ ]:
df = df.rename(columns={"parental level of education": "education", "test preparation course": "test preparation"})
df

     gender race/ethnicity  ... reading score writing score
0    female        group B  ...            72            74
1    female        group C  ...            90            88
2    female        group B  ...            95            93
3      male        group A  ...            57            44
4      male        group C  ...            78            75
..      ...            ...  ...           ...           ...
995  female        group E  ...            99            95
996    male        group C  ...            55            55
997  female        group C  ...            71            65
998  female        group D  ...            78            77
999  female        group D  ...            86            86

[1000 rows x 9 columns]

## **Минимальный балл для сдачи экзамена**## 
Переменную `passmark` будем использовать со значеним 50 в качестве минимального балла для сдачи экзамена.

In [ ]:
passmark = 50

## **Задание 10.**## 
Ответим на слудеющие вопросы:
* Какая доля студентов сдала экзамен по математике (passmark >= 50)?
* Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
* Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

### Доля студентов, сдавших экзамен по математике

In [ ]:
studentsPassedMathPropDf = TestDf[TestDf['math score'] >= passmark]
studentsPassedMathProp = studentsPassedMathPropDf.shape[0]/df.shape[0]
print('Доля сдавших экзамен по математике: ', studentsPassedMathProp)

Доля сдавших экзамен по математике:  0.865

### Доля студентов, проходивших курс подготовки и сдавших экзамен

In [ ]:
studentsPassedMathAndTrainingPropDf = studentsPassedMathPropDf[studentsPassedMathPropDf['test preparation course']=='completed']
studentsPassedMathAndTrainingProp = studentsPassedMathAndTrainingPropDf.shape[0]/studentsPassedPrepTest.shape[0]
print('Доля студентов, \033[1m проходивших курс подготовки \033[0m и сдавших экзамен: ', studentsPassedMathAndTrainingProp)

Доля студентов,  проходивших курс подготовки  и сдавших экзамен:  0.9217877094972067

### Доля женщин, не проходивших курс подготовки к экзамену и не сдавших экзамен по математике

Для решения задачи обращаться буду к ранее заготовленному датафрейму TestDf, содержащему: пол, подготовительный курс, баллы по трем предметам

In [ ]:
TestDf

     gender test preparation course  math score  reading score  writing score
0    female                    none          72             72             74
1    female               completed          69             90             88
2    female                    none          90             95             93
3      male                    none          47             57             44
4      male                    none          76             78             75
..      ...                     ...         ...            ...            ...
995  female               completed          88             99             95
996    male                    none          62             55             55
997  female               completed          59             71             65
998  female               completed          68             78             77
999  female                    none          77             86             86

[1000 rows x 5 columns]

In [ ]:
womenDidntPassMathAndTraining = TestDf[(TestDf["math score"] < passmark) & (TestDf['gender'] == 'female') & (TestDf['test preparation course'] == 'none')]
womenDidntPassMathAndTraining

     gender test preparation course  math score  reading score  writing score
9    female                    none          38             60             50
17   female                    none          18             32             28
55   female                    none          33             41             43
59   female                    none           0             17             10
69   female                    none          39             64             57
..      ...                     ...         ...            ...            ...
961  female                    none          48             54             53
973  female                    none          49             65             61
980  female                    none           8             24             23
986  female                    none          40             59             51
988  female                    none          44             45             45

[70 rows x 5 columns]

Девушек, не сдавших экзамен по математике и не проходивших при этом подготовительный курс, оказалось 78. <br>
Теперь мы можем выявить их долю в общем числе девушек

In [ ]:
womenNum = df[df['gender'] == 'female'].shape[0] 
womenDidntPassMathAndTrainingProp = womenDidntPassMathAndTraining.shape[0] / womenNum
print('Доля женщин, \033[1m не проходивших курс подготовки \033[0m к экзамену и \033[1m не сдавших экзамен \033[0m по математике', womenDidntPassMathAndTrainingProp)

Доля женщин,  не проходивших курс подготовки  к экзамену и  не сдавших экзамен  по математике 0.13513513513513514

## **Задание 11.**## 
 С помощью groupby выполним задания ниже. Также выведем время выполнения каждого из заданий.
* Для каждой этнической группы выведем средний балл за экзамен по чтению
* Для каждого уровня образования выведем минимальный балл за экзамен по письму

In [ ]:
import timeit

### Для каждой этнической группы выведем средний балл за экзамен по чтению

In [ ]:
def getAvgScoreByEthnicGroup():
  ethnicGroups = df['race/ethnicity'].unique().tolist()
  ethnicGroupsAvgScoreDf = df.groupby('race/ethnicity')['reading score'].mean()
  return ethnicGroupsAvgScoreDf

getAvgScoreByEthnicGroup()

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64

Время выполнения (х100):

In [ ]:
print(timeit.timeit(getAvgScoreByEthnicGroup, number=100))

0.117363188000013

### Для каждого уровня образования выведем минимальный балл за экзамен по письму

In [ ]:
def GetAvgScoreByEducation():
  educationGroups = df['education'].unique().tolist()
  educationGroupsAvgScoreDf = df.groupby('education')['writing score'].mean()
  return educationGroupsAvgScoreDf

GetAvgScoreByEducation()

education
associate's degree    69.896396
bachelor's degree     73.381356
high school           62.448980
master's degree       75.677966
some college          68.840708
some high school      64.888268
Name: writing score, dtype: float64

Время выполнения (х100):

In [ ]:
print(timeit.timeit(GetAvgScoreByEducation, number=100))

0.12168248099999346

## **Задание 12.**## 
Выполним задание 11 с помощью циклов и сравним время выполнения.

### Для каждой этнической группы выведем средний балл за экзамен по чтению

In [ ]:
def showAvgScoreByEthnicGroup():
  ethnicGroups = df['race/ethnicity'].unique()
  avgScores = []
  for i in ethnicGroups:
    ethnicGroup = df[df['race/ethnicity'] == i]
    avgScores.append(ethnicGroup['reading score'].mean())
  avgScoresDf = pd.DataFrame({'race/ethnicity': [i for i in ethnicGroups], 'Avg reading score':avgScores})
  return avgScoresDf

showAvgScoreByEthnicGroup()

  race/ethnicity  Avg reading score
0        group B          67.352632
1        group C          69.103448
2        group A          64.674157
3        group D          70.030534
4        group E          73.028571

Время выполнения (х100):

In [ ]:
print(timeit.timeit(showAvgScoreByEthnicGroup, number=100))

0.3932598370000733

### Для каждого уровня образования выведем минимальный балл за экзамен по письму

In [ ]:
def showAvgScoreByEducation():
  educationGroups = df['education'].unique()
  avgScores = []
  for ed in educationGroups:
    educationGroup = df[df['education'] == ed]
    avgScores.append(educationGroup['writing score'].mean())
  avgScoresDf = pd.DataFrame({'education': [i for i in educationGroups], 'Avg writing score':avgScores})
  return avgScoresDf

showAvgScoreByEducation()

            education  Avg writing score
0   bachelor's degree          73.381356
1        some college          68.840708
2     master's degree          75.677966
3  associate's degree          69.896396
4         high school          62.448980
5    some high school          64.888268

Время выполнения (х100):

In [ ]:
print(timeit.timeit(showAvgScoreByEducation, number=100))

0.46106133099999624

## **Задание 13.**
Выведем на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. <br>
То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выведем средний балл по каждому из предметов.

In [ ]:
grouped = pd.pivot_table(df, index=['gender', 'education'])
grouped

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

Проверим средний балл по математике (`math score`) для девушек (`female`) со степень ассоциата (`associate's degree`)

In [ ]:
avgScoreFemAssociate = df[(df['gender'] == 'female') & (df['education'] == "associate's degree")]['math score'].mean()
avgScoreFemAssociate

65.25

Как видим, всё сошлось

## **Задание 14.**
**Узнаем, сколько студентов успешно сдали экзамен по математике.** <br>
* Для этого создадим новый столбец в таблице df под названием Math_PassStatus и запишем в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

* Затем посчитаем количество студентов, сдавших и не сдавших экзамен по математике.

* А после сделаем аналогичные шаги для экзаменов по чтению и письму.

### 1. Создадим новый столбец в таблице df под названием Math_PassStatus и запишем в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе

In [ ]:
df['Math_PassStatus'] = 'F'
df.loc[df['math score'] >= passmark, 'Math_PassStatus'] = 'P'
df

     gender race/ethnicity  ... writing score Math_PassStatus
0    female        group B  ...            74               P
1    female        group C  ...            88               P
2    female        group B  ...            93               P
3      male        group A  ...            44               F
4      male        group C  ...            75               P
..      ...            ...  ...           ...             ...
995  female        group E  ...            95               P
996    male        group C  ...            55               P
997  female        group C  ...            65               P
998  female        group D  ...            77               P
999  female        group D  ...            86               P

[1000 rows x 10 columns]

### 2. Посчитаем количество студентов, сдавших и не сдавших экзамен по математике.

In [ ]:
studensPassedMathTest = df[df['Math_PassStatus'] == 'P'].count()[0]
studensDidntPassMathTest = df[df['Math_PassStatus'] == 'F'].count()[0]
print({'Сдавшие экзамен по математике': studensPassedMathTest, 'Не сдавшие': studensDidntPassMathTest})

{'Сдавшие экзамен по математике': 865, 'Не сдавшие': 135}

### 3. Повторим шаги для экзаменов по чтению и письму

In [ ]:
def examsStatusCols(df, examName, outro):
  df[f'{examName.title()}_PassStatus'] = 'F'
  df.loc[df[f'{examName} score'] >= passmark, f'{examName.title()}_PassStatus'] = 'P'
  studensPassedTest = df[df[f'{examName.title()}_PassStatus'] == 'P'].count()[0]
  studensDidntPassTest = df[df[f'{examName.title()}_PassStatus'] == 'F'].count()[0]
  print({f'Сдавшие экзамен по {outro}': studensPassedTest, 'Не сдавшие': studensDidntPassTest})
  return df

#### 3.1. Экзамен по чтению

In [ ]:
examsStatusCols(df,'reading', 'чтению')

{'Сдавшие экзамен по чтению': 910, 'Не сдавшие': 90}

     gender race/ethnicity  ... Math_PassStatus Reading_PassStatus
0    female        group B  ...               P                  P
1    female        group C  ...               P                  P
2    female        group B  ...               P                  P
3      male        group A  ...               F                  P
4      male        group C  ...               P                  P
..      ...            ...  ...             ...                ...
995  female        group E  ...               P                  P
996    male        group C  ...               P                  P
997  female        group C  ...               P                  P
998  female        group D  ...               P                  P
999  female        group D  ...               P                  P

[1000 rows x 11 columns]

#### 3.2 Экзамен по письму

In [ ]:
examsStatusCols(df,'writing', 'письму')

{'Сдавшие экзамен по письму': 886, 'Не сдавшие': 114}

     gender race/ethnicity  ... Reading_PassStatus Writing_PassStatus
0    female        group B  ...                  P                  P
1    female        group C  ...                  P                  P
2    female        group B  ...                  P                  P
3      male        group A  ...                  P                  F
4      male        group C  ...                  P                  P
..      ...            ...  ...                ...                ...
995  female        group E  ...                  P                  P
996    male        group C  ...                  P                  P
997  female        group C  ...                  P                  P
998  female        group D  ...                  P                  P
999  female        group D  ...                  P                  P

[1000 rows x 12 columns]

### **Результат**
В результате получаем следующую таблицу:

In [ ]:
df

     gender race/ethnicity  ... Reading_PassStatus Writing_PassStatus
0    female        group B  ...                  P                  P
1    female        group C  ...                  P                  P
2    female        group B  ...                  P                  P
3      male        group A  ...                  P                  F
4      male        group C  ...                  P                  P
..      ...            ...  ...                ...                ...
995  female        group E  ...                  P                  P
996    male        group C  ...                  P                  P
997  female        group C  ...                  P                  P
998  female        group D  ...                  P                  P
999  female        group D  ...                  P                  P

[1000 rows x 12 columns]

## **Задание 15.**
**Узнаем, сколько студентов успешно сдали экзамены.** <br>
* Создадим столбец OverAll_PassStatus и запишем в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

* Посчитаем количество студентов, которые сдали все экзамены.

#### Создадим столбец OverAll_PassStatus и запишем в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'

In [ ]:
df['OverAll_PassStatus'] = 'F'
df.loc[((df['Math_PassStatus'] == 'P') & (df['Reading_PassStatus'] == 'P') & (df['Writing_PassStatus'] == 'P')), 'OverAll_PassStatus'] = 'P'
df

     gender race/ethnicity  ... Writing_PassStatus OverAll_PassStatus
0    female        group B  ...                  P                  P
1    female        group C  ...                  P                  P
2    female        group B  ...                  P                  P
3      male        group A  ...                  F                  F
4      male        group C  ...                  P                  P
..      ...            ...  ...                ...                ...
995  female        group E  ...                  P                  P
996    male        group C  ...                  P                  P
997  female        group C  ...                  P                  P
998  female        group D  ...                  P                  P
999  female        group D  ...                  P                  P

[1000 rows x 13 columns]

### Посчитаем количество студентов, которые сдали все экзамены.

In [ ]:
studentsPassedAllExamsNum = df[df['OverAll_PassStatus'] == 'P'].shape[0]
print('Число студентов, сдавших все 3 экзамена: ', studentsPassedAllExamsNum)

Число студентов, сдавших все 3 экзамена:  812

## **Задание 16.**
**Переведем баллы в оценки.** <br>

<u>Система перевода баллов в оценки</u><br>
где $x$ – средний балл студента по трём экзаменам
> $A$ для $x > 90$ <br>
> $B$ для  $x \in [80, 90]$ <br>
> $C$ для  $x \in [70, 80]$ <br>
> $D$ для  $x \in [60, 70]$ <br>
> $E$ для  $x \in [50, 60]$ <br>
> $F$ для  $x < 50 $ <br>

* Создадим вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

* Создадим столбец Grade и запишите в него оценку каждого студента.

* Выведем количество студентов, получивших каждую из оценок.

#### 1. Воспользуемся таблицей `subjectsDf`, созданной в 6 задании

In [ ]:
subjectsDf

     math score  reading score  writing score       mean
0            72             72             74  72.666667
1            69             90             88  82.333333
2            90             95             93  92.666667
3            47             57             44  49.333333
4            76             78             75  76.333333
..          ...            ...            ...        ...
995          88             99             95  94.000000
996          62             55             55  57.333333
997          59             71             65  65.000000
998          68             78             77  74.333333
999          77             86             86  83.000000

[1000 rows x 4 columns]

#### 2. Создадим функицю `mark`, возвращающую оценку, исходя из диапозона, в который попадает средний балл студента по трём экзаменам

In [ ]:
gradesDict = {90: 'A', 80: 'B', 70: 'C', 60: 'D', 49.999: 'E', -1: 'F'}

def mark(studentsMark):
  for g in gradesDict.keys():
    if studentsMark > g:
      return gradesDict.get(g)
      break
    else:
      continue
  
print({'score>=50': mark(50), 'score<50': mark(49), 'score=60': mark(60), 'score=90': mark(90), 'score>90': mark(95)})

{'score>=50': 'E', 'score<50': 'F', 'score=60': 'E', 'score=90': 'B', 'score>90': 'A'}

#### 3. Добавим в исходную таблицу `df` столбец `Mean score` со средним баллом студента, взятым из столбца `mean` таблицы `subjectDf`.

* Добавим также столбец `Grade`, в который будем выставлять оценку в соответствии с требованиями выше. В этом нам поможет функция `mark`

In [ ]:
df['Mean score'] = subjectsDf['mean']
df['Grade'] = df['Mean score'].apply(lambda x: mark(x))
df

     gender race/ethnicity  ... Grade Mean score
0    female        group B  ...     C  72.666667
1    female        group C  ...     B  82.333333
2    female        group B  ...     A  92.666667
3      male        group A  ...     F  49.333333
4      male        group C  ...     C  76.333333
..      ...            ...  ...   ...        ...
995  female        group E  ...     A  94.000000
996    male        group C  ...     E  57.333333
997  female        group C  ...     D  65.000000
998  female        group D  ...     C  74.333333
999  female        group D  ...     B  83.000000

[1000 rows x 15 columns]